openapi: 3.0.0
info:
  description: |
    This is a sample Weather server.
  version: "1.0.0"
  title: Weather, Sunset, Sunrise API
  termsOfService: 'http://swagger.io/terms/'
  contact:
    email: fabiosantos673@gmail.com
servers:
# Added by API Auto Mocking Plugin
- description: SwaggerHub API Auto Mocking
  url: https://virtserver.swaggerhub.com/FabioTomaz/Weather/1.0.0
- description: Localhost
  url: 'http://localhost:3000'
tags:
- name: city
  description: Operations about cities
paths:
  /api/data:
    get:
      tags:
      - city
      summary: Get city by city name
      operationId: getCitiesData
      parameters:
      - in: query
        name: cities
        schema:
          type: array
          items:
            type: string
          example: ["Aveiro", "London", "New York"]
        description: The numbers of items to return
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CityArray'
        '404':
          description: One of the cities were not found
  '/api/data/{cityName}':
    get:
      tags:
      - city
      summary: Get city by city name
      operationId: getCityData
      parameters:
      - name: cityName
        in: path
        description: The name that needs to be fetched. Use Aveiro for testing.
        required: true
        example: "Aveiro"
        schema:
          type: string
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/City'
        '404':
          description: City not found
components:
  schemas:
    City:
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        temp:
          type: string
        lat:
          type: number
        lng:
          type: number
        sunset:
          type: string
        sunrise:
          type: string
    CityArray:
      type: array
      items:
        $ref: '#/components/schemas/City'
      description: List of city object
